name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: run autograder
      run: |
        python autograder.py > gradeFile.txt
  autograde:
    steps:
    - name: question 1 result
      run: |
        ./grader.sh q1
    - name: question 2 result
      run: |
        ./grader.sh q2
    - name: question 3 result
      run: |
        ./grader.sh q3
    - name: question 4 result
      run: |
        ./grader.sh q4
    - name: question 5 result
      run: |
        ./grader.sh q5
